
#pragma once

#define IRR_VERSION_MAJOR    1
#define IRR_VERSION_MINOR    9
#define IRR_VERSION_REVISION 0
#define IRR_VERSION_STATUS   ""

#define CVAUX_STR_EXP(__A)  #__A
#define CVAUX_STR(__A)      CVAUX_STR_EXP(__A)

#define CVAUX_STRW_EXP(__A)  L ## #__A
#define CVAUX_STRW(__A)      CVAUX_STRW_EXP(__A)

#define IRR_VERSION          CVAUX_STR(IRR_VERSION_MAJOR) "." CVAUX_STR(IRR_VERSION_MINOR) "." CVAUX_STR(IRR_VERSION_REVISION) IRR_VERSION_STATUS

/* old  style version constants*/
#define IRR_MAJOR_VERSION    IRR_VERSION_MAJOR
#define IRR_MINOR_VERSION    IRR_VERSION_MINOR
#define IRR_SUBMINOR_VERSION IRR_VERSION_REVISION

