
file(STRINGS "${QVR_VERSION_FILE}" QVR_VERSION_PARTS REGEX "#define ${QVR_VERSION_ID}_VERSION_[A-Z]+[ ]+" )

string(REGEX REPLACE ".+${QVR_VERSION_ID}_VERSION_MAJOR[ ]+([0-9]+).*" "\\1" QVR_VERSION_MAJOR "${QVR_VERSION_PARTS}")
string(REGEX REPLACE ".+${QVR_VERSION_ID}_VERSION_MINOR[ ]+([0-9]+).*" "\\1" QVR_VERSION_MINOR "${QVR_VERSION_PARTS}")
string(REGEX REPLACE ".+${QVR_VERSION_ID}_VERSION_REVISION[ ]+([0-9]+).*" "\\1" QVR_VERSION_PATCH "${QVR_VERSION_PARTS}")
string(REGEX REPLACE ".+${QVR_VERSION_ID}_VERSION_STATUS[ ]+\"([^\"]*)\".*" "\\1" QVR_VERSION_STATUS "${QVR_VERSION_PARTS}")

set(QVR_VERSION_PLAIN "${QVR_VERSION_MAJOR}.${QVR_VERSION_MINOR}.${QVR_VERSION_PATCH}")
set(QVR_VERSION "${QVR_VERSION_PLAIN}${QVR_VERSION_STATUS}")
set(QVR_SOVERSION "${QVR_VERSION_MAJOR}.${QVR_VERSION_MINOR}")
set(QVR_LIBVERSION "${QVR_VERSION_MAJOR}.${QVR_VERSION_MINOR}.${QVR_VERSION_PATCH}")

# create a dependency on the version file
# we never use the output of the following command but cmake will rerun automatically if the version file changes
configure_file("${QVR_VERSION_FILE}" "${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/_junk/version.junk" COPYONLY)
